// ui/statusCopy.js — every status key of SPEC §8.4, exactly (ARCH §3.12.5). P1 discovery … P5 idle facts.
// Template: {var} substitutes; {var:one|few|many} is the Russian plural word for var (core/ru.js plural()).
// {name} is WORLD.operator.name as written (capitalised); the caller passes it.
export const STATUS_COPY = Object.freeze({
  'boot.pointer': { text: 'вижу тебя.', p: 3 },
  'boot.nopointer': { text: 'система проснулась.', p: 3 },
  'return.sameDay': { text: 'снова ты.', p: 3 },
  'return.days': { text: 'ты вернулся. тебя не было {N} {N:день|дня|дней}.', p: 3 },
  'return.days.owner': { text: 'привет, {name}. тебя не было {N} {N:день|дня|дней}.', p: 3 },
  'return.node': { text: 'пока тебя не было: +1 узел.', p: 2 },
  'night': { text: 'спокойной ночи, {name}.', p: 3 },
  'drowsy': { text: 'скоро ночь.', p: 3 },
  'night.flinch': { text: 'ещё не сплю.', p: 1 },
  'tab.back': { text: 'вот ты где.', p: 3 },
  'drawing.boot': { text: 'помню твой рисунок.', p: 3 },
  'drawing.saved': { text: 'запомнил.', p: 1 },
  'glyph.saved': { text: 'запомнил.', p: 1 },
  'probe.sent': { text: 'зонд {code} в пути. вернётся завтра.', p: 1 },
  'probe.back': { text: 'зонд {code} вернулся. есть запись.', p: 2 },
  'transmission.new': { text: 'пришла передача.', p: 2 },
  'mission.decoded': { text: 'вылазка {code} расшифрована.', p: 2 },
  'companion.far': { text: 'кто-то летит к нам.', p: 2 },
  'companion.near': { text: 'он ближе. осталось {n} {n:день|дня|дней}.', p: 2 },
  'companion.arrived': { text: 'он прилетел. его зовут {name}.', p: 1 },
  'capsule.open': { text: 'капсула открыта.', p: 1 },
  'birthday': { text: 'с днём рождения, {name}!', p: 2 },
  'anniversary': { text: 'сегодня {title}. {years} {years:год|года|лет} назад.', p: 2 },
  'found': { text: 'найдено.', p: 1 },
  'shard': { text: 'осколок {k} из 5 на месте.', p: 1 },
  'nadir.open': { text: 'внизу что-то открылось.', p: 1 },
  'rank': { text: 'новый ранг: {rank}.', p: 1 },
  'dizzy': { text: 'всё кружится.', p: 1 },
  'dizzy.after': { text: 'уже лучше.', p: 1 },
  'whale': { text: 'смотри. кит.', p: 1 },
  'drone': { text: 'дрон принёс шутку.', p: 1 },
  'pull': { text: 'ты всё ещё внутри sam.vin.', p: 1 },
  'relaunch': { text: 'сплю. разбуди меня.', p: 1 },
  'member.typed': { text: '{callsign} на связи.', p: 1 },
  'hint.done': { text: 'пока всё найдено.', p: 1 },
  'hint.time': { text: 'остальное придёт само. возвращайся.', p: 1 },
  'sealed': { text: 'запечатано. осколков {k} из 5.', p: 1 },
  'route.missing': { text: 'здесь ничего нет. пока.', p: 1 },
  'idle.nodes': { text: '{n} {n:узел|узла|узлов} горит.', p: 5 },
  'idle.mission': { text: 'вылазка {code} ждёт.', p: 5 },
});
