/* ОПИСЬ ПРИЗОВ СУНДУКА — ЕДИНСТВЕННЫЙ ИСТОЧНИК (D-255).
 *
 * ПОВОД, дословно от основателя 22.09.2026: «нужно придумать 30 самых
 * гениальных и приятных призов для пользователей … призы в сундуках должны
 * быть стоящими и создавать впечатление у пользователя персонализации и
 * уникальности».
 *
 * ПРАВИЛО, ПО КОТОРОМУ ОТБИРАЛИСЬ ПРИЗЫ. Приз — это вещь ЭТОЙ СИСТЕМЫ,
 * которую она может дать сама, на этом устройстве, без сервера и без чужого
 * согласия. Не купон, не обещание, не скидка: у Совета нет права обещать
 * деньги основателя, и у системы нет сервера, чтобы что-то прислать.
 * Впечатление уникальности здесь не впечатление: цвет выведен из имени, знак
 * — из имени и дня рождения системы, номер — из соли замка, письма — из
 * настоящих чисел, эхо — из собственных слов. У двух людей одинаковых не
 * бывает.
 *
 * kind — род, который умеет выдать движок (os/apps/chest/chest.js). Приз с
 * родом, которого движок не умеет, — обещание двери, которая не
 * открывается; закон tools/chest-check.mjs требует, чтобы таких не было, и
 * открывает все тридцать, проверяя след каждого там, где приз живёт.
 *
 * params.probe — чем закон проверяет команду (не то же, что имя команды,
 * когда команде нужен довод).
 *
 * tier — род радости, по слову основателя: joy — ежедневная радость (частые,
 * приятны сразу), discovery — личная находка, rare — редкий момент. Порядок
 * случаен, но первый сундук — всегда joy, а редкое не выпадает раньше
 * восьмого дня: удивление, а не разочарование.
 * switch — приз, который меняет систему сам по себе; человек вправе его
 * выключить, не теряя: «получить вещь и иметь право не пользоваться — тоже
 * часть владения» (основатель).
 */
window.SB_PRIZES = [
  /* ── КОМНАТЫ: ПЯТЬ НОВЫХ, ОДНА ИЗ НИХ — ТОЛЬКО ВАША ───────────────────── */
  { id: "own-room", kind: "mood", params: { mood: "own" }, tier: "rare",
    title: { en: "A room of your own", ru: "Своя комната", ee: "Sinu oma tuba" },
    what: { en: "A tenth room among the rooms in Settings. Its light is derived from your name — no one else has this exact hue.",
            ru: "Десятая комната среди комнат в Настройках. Её свет выведен из вашего имени — такого тона нет ни у кого другого.",
            ee: "Kümnes tuba Seadete tubade seas. Selle valgus on tuletatud sinu nimest — sellist tooni pole kellelgi teisel." },
    where: "settings" },
  { id: "midnight", kind: "mood", params: { mood: "midnight" }, tier: "joy",
    title: { en: "Midnight", ru: "Полночь", ee: "Kesköö" },
    what: { en: "A deep blue room for the last hour of the day. Calm ring, narrow band, no glare.",
            ru: "Глубокая синяя комната для последнего часа дня. Спокойное кольцо, узкий пояс, без бликов.",
            ee: "Sügavsinine tuba päeva viimaseks tunniks. Rahulik ring, kitsas vöö, ilma pimestamata." },
    where: "settings" },
  { id: "garden", kind: "mood", params: { mood: "garden" }, tier: "joy",
    title: { en: "Garden", ru: "Сад", ee: "Aed" },
    what: { en: "A green room that breathes slowly. Leaf light, not screen light.",
            ru: "Зелёная комната, которая дышит медленно. Свет листвы, а не экрана.",
            ee: "Roheline tuba, mis hingab aeglaselt. Lehtede valgus, mitte ekraani oma." },
    where: "settings" },
  { id: "lavender", kind: "mood", params: { mood: "lavender" }, tier: "joy",
    title: { en: "Lavender", ru: "Лаванда", ee: "Lavendel" },
    what: { en: "A violet room for evenings. Softer than Aurora, warmer than Mono.",
            ru: "Фиолетовая комната для вечеров. Мягче Авроры, теплее Моно.",
            ee: "Lilla tuba õhtuteks. Pehmem kui Virmalised, soojem kui Mono." },
    where: "settings" },
  { id: "honey", kind: "mood", params: { mood: "honey" }, tier: "joy",
    title: { en: "Honey", ru: "Мёд", ee: "Mesi" },
    what: { en: "A golden room. The brightest of the calm rooms — for mornings when the desk should glow.",
            ru: "Золотая комната. Самая светлая из спокойных — для утра, когда стол должен светиться.",
            ee: "Kuldne tuba. Rahulikest tubadest heledaim — hommikuteks, mil laud peaks helendama." },
    where: "settings" },

  /* ── ВЕЩИ, КОТОРЫХ НЕТ НИ У КОГО ДРУГОГО ───────────────────────────────
   Пять призов-файлов SVG (знак, созвездие, год в круге, свидетельство,
   портрет) сняты 22.09.2026 по слову основателя: «это вовсе не подарок …
   большая часть пользователей будет равнодушна». Взамен — пять вещей,
   которые человек чувствует каждый день (ниже, «ЖИВОЕ»). */
  { id: "serial", kind: "serial", params: {}, tier: "discovery",
    title: { en: "Your system's number", ru: "Номер вашей системы", ee: "Sinu süsteemi number" },
    what: { en: "Twelve characters no other system has. Derived from your lock's salt when the lock is set, otherwise from random bytes drawn here once. Shown in the account window.",
            ru: "Двенадцать знаков, которых нет ни у одной другой системы. Выведены из соли вашего замка, если замок стоит, иначе — из случайных байтов, взятых здесь один раз. Стоит в окне аккаунта.",
            ee: "Kaksteist märki, mida ühelgi teisel süsteemil pole. Tuletatud sinu luku soolast, kui lukk on peal, muidu siin üks kord võetud juhuslikest baitidest. Näha konto aknas." },
    where: "account" },
  { id: "stamp", kind: "stamp", params: {}, tier: "discovery", switch: true,
    title: { en: "Your sign on every note", ru: "Ваш знак на каждой заметке", ee: "Sinu märk igal märkmel" },
    what: { en: "A faint print of your sign in the corner of every sticky note. Nobody else's notes carry it.",
            ru: "Едва заметный оттиск вашего знака в углу каждой заметки на столе. На чужих заметках его нет.",
            ee: "Sinu märgi õrn jäljend iga laual oleva märkme nurgas. Kellegi teise märkmetel seda pole." },
    where: "notes" },

  /* ── СЛОВА, КОТОРЫЕ ЗНАЮТ ВАС ПО ИМЕНИ ───────────────────────────────── */
  { id: "tagline", kind: "word", params: { word: "tagline" }, tier: "discovery", switch: true,
    title: { en: "Your name at the door", ru: "Ваше имя на входе", ee: "Sinu nimi uksel" },
    what: { en: "The line on the sign-in card now ends with your name instead of «baby».",
            ru: "Строка на карточке входа теперь кончается вашим именем, а не «baby».",
            ee: "Sisselogimiskaardi rida lõpeb nüüd sinu nimega, mitte sõnaga «baby»." },
    where: "login" },
  { id: "farewell", kind: "word", params: { word: "farewell" }, tier: "discovery", switch: true,
    title: { en: "A farewell by name", ru: "Прощание по имени", ee: "Hüvastijätt nimepidi" },
    what: { en: "When you sign out, the system says goodbye to you, not to «baby».",
            ru: "Когда вы выходите, система прощается с вами, а не с «baby».",
            ee: "Kui sa välja logid, jätab süsteem hüvasti sinuga, mitte «baby'ga»." },
    where: "login" },
  { id: "greeting", kind: "word", params: { word: "greeting" }, tier: "discovery", switch: true,
    title: { en: "The terminal knows you", ru: "Терминал знает вас", ee: "Terminal tunneb sind" },
    what: { en: "The terminal opens with your name and the number of days you have kept this system.",
            ru: "Терминал открывается вашим именем и числом дней, которые вы держите эту систему.",
            ee: "Terminal avaneb sinu nime ja päevade arvuga, mil sa seda süsteemi hoidnud oled." },
    where: "terminal" },
  { id: "title", kind: "title", params: {}, tier: "discovery", switch: true,
    title: { en: "A title", ru: "Титул", ee: "Tiitel" },
    what: { en: "Choose one of four — Keeper, Warden, Gardener, Night watch. It stands under your name in the account window.",
            ru: "Выберите один из четырёх — Хранитель, Смотритель, Садовник, Ночной сторож. Он стоит под вашим именем в окне аккаунта.",
            ee: "Vali üks neljast — Hoidja, Valvur, Aednik, Öövaht. See seisab sinu nime all konto aknas." },
    where: "account" },

  /* ── ДЕСЯТЬ КОМАНД ТЕРМИНАЛА ─────────────────────────────────────────── */
  { id: "coin", kind: "command", params: { cmd: "coin" }, tier: "joy",
    title: { en: "A coin", ru: "Монетка", ee: "Münt" },
    what: { en: "Type «coin» in the terminal. Heads or tails, from the browser's own random bytes.",
            ru: "Наберите «coin» в терминале. Орёл или решка — из случайных байтов самого браузера.",
            ee: "Kirjuta terminali «coin». Kull või kiri — brauseri enda juhuslikest baitidest." },
    where: "terminal" },
  { id: "dice", kind: "command", params: { cmd: "dice", probe: "dice 20" }, tier: "joy",
    title: { en: "A die", ru: "Кость", ee: "Täring" },
    what: { en: "«dice» throws a six; «dice 20» throws a twenty. Any number of sides.",
            ru: "«dice» бросает шестигранник; «dice 20» — двадцатигранник. Граней — сколько скажете.",
            ee: "«dice» viskab kuuetahulist; «dice 20» kahekümnetahulist. Tahke nii palju kui ütled." },
    where: "terminal" },
  { id: "pick", kind: "command", params: { cmd: "pick", probe: "pick tea, coffee, water" }, tier: "joy",
    title: { en: "Let the system choose", ru: "Пусть выберет система", ee: "Las süsteem valib" },
    what: { en: "«pick tea, coffee, water» — one of them comes back. For the days when choosing is the hard part.",
            ru: "«pick чай, кофе, вода» — вернётся одно из них. Для дней, когда выбрать труднее всего.",
            ee: "«pick tee, kohv, vesi» — üks neist tuleb tagasi. Päevadeks, mil valimine on kõige raskem." },
    where: "terminal" },
  { id: "timer", kind: "command", params: { cmd: "timer", probe: "timer 1" }, tier: "joy",
    title: { en: "A timer", ru: "Таймер", ee: "Taimer" },
    what: { en: "«timer 25» — twenty-five minutes, then the desk tells you. «timer stop» cancels.",
            ru: "«timer 25» — двадцать пять минут, потом стол скажет. «timer stop» отменяет.",
            ee: "«timer 25» — kakskümmend viis minutit, siis laud ütleb. «timer stop» tühistab." },
    where: "terminal" },
  { id: "days", kind: "command", params: { cmd: "days", probe: "days 2027-01-01" }, tier: "joy",
    title: { en: "Counting days", ru: "Счёт дней", ee: "Päevade lugemine" },
    what: { en: "«days 2027-01-01» — how many days until or since a date, and what weekday it falls on.",
            ru: "«days 2027-01-01» — сколько дней до даты или после неё, и какой это день недели.",
            ee: "«days 2027-01-01» — mitu päeva kuupäevani või sellest möödas, ja mis nädalapäev see on." },
    where: "terminal" },
  { id: "when", kind: "command", params: { cmd: "when", probe: "when tokyo" }, tier: "joy",
    title: { en: "What time is it there", ru: "Который час там", ee: "Mis kell seal on" },
    what: { en: "«when tokyo» — the time in another city right now, from the browser's own zone table. No network.",
            ru: "«when tokyo» — который час сейчас в другом городе, из таблицы поясов самого браузера. Без сети.",
            ee: "«when tokyo» — mis kell on praegu teises linnas, brauseri enda ajavööndite tabelist. Ilma võrguta." },
    where: "terminal" },
  { id: "moon", kind: "command", params: { cmd: "moon" }, tier: "discovery",
    title: { en: "The moon", ru: "Луна", ee: "Kuu" },
    what: { en: "«moon» — tonight's phase, how much of it is lit, and when it is next full. Computed here, not fetched.",
            ru: "«moon» — фаза этой ночи, сколько её освещено и когда ближайшее полнолуние. Посчитано здесь, а не скачано.",
            ee: "«moon» — tänase öö faas, kui palju on valgustatud ja millal on järgmine täiskuu. Arvutatud siin, mitte alla laaditud." },
    where: "terminal" },
  { id: "sun", kind: "command", params: { cmd: "sun", probe: "sun 59.44 24.75" }, tier: "discovery",
    title: { en: "The sun", ru: "Солнце", ee: "Päike" },
    what: { en: "«sun 59.44 24.75» — sunrise and sunset today for those coordinates. Astronomy in the terminal, no location asked.",
            ru: "«sun 59.44 24.75» — восход и закат сегодня для этих координат. Астрономия в терминале, без запроса местоположения.",
            ee: "«sun 59.44 24.75» — päikesetõus ja -loojang täna neil koordinaatidel. Astronoomia terminalis, asukohta küsimata." },
    where: "terminal" },
  { id: "quiet", kind: "command", params: { cmd: "quiet", probe: "quiet 1" }, tier: "joy",
    title: { en: "An hour of quiet", ru: "Час тишины", ee: "Vaikuse tund" },
    what: { en: "«quiet 60» — do not disturb for sixty minutes, then it lifts itself. No notice will interrupt you.",
            ru: "«quiet 60» — не беспокоить шестьдесят минут, потом снимается само. Ни одно извещение не перебьёт вас.",
            ee: "«quiet 60» — mitte segada kuuskümmend minutit, siis tühistub ise. Ükski teade ei sega sind." },
    where: "terminal" },
  { id: "chronicle", kind: "command", params: { cmd: "chronicle" }, tier: "discovery",
    title: { en: "Chronicle", ru: "Летопись", ee: "Kroonika" },
    what: { en: "«chronicle» — your system in numbers: days kept, notes, words written, envelopes sealed, chests opened. Asked from the system, never remembered.",
            ru: "«chronicle» — ваша система в числах: дней, записей, написанных слов, запечатанных конвертов, открытых сундуков. Спрошено у системы, а не запомнено.",
            ee: "«chronicle» — sinu süsteem arvudes: päevi, märkmeid, kirjutatud sõnu, pitseeritud ümbrikke, avatud laekaid. Küsitud süsteemilt, mitte meelde jäetud." },
    where: "terminal" },
  { id: "note-cmd", kind: "command", params: { cmd: "note", probe: "note buy bread" }, tier: "joy",
    title: { en: "A note from the terminal", ru: "Заметка из терминала", ee: "Märge terminalist" },
    what: { en: "«note buy bread» — a sticky note appears on the desk without leaving the terminal.",
            ru: "«note купить хлеб» — заметка появляется на столе, не выходя из терминала.",
            ee: "«note osta leiba» — märge ilmub lauale terminalist lahkumata." },
    where: "terminal" },

  /* ── ТО, ЧТО ВОЗВРАЩАЕТ ВАМ ВАШЕ ЖЕ ──────────────────────────────────── */
  { id: "echo", kind: "echo", params: {}, tier: "joy", switch: true,
    title: { en: "An echo", ru: "Эхо", ee: "Kaja" },
    what: { en: "Each day the chest shows one line you wrote yourself, and how long ago. Your words, back to you — and they never leave this device.",
            ru: "Каждый день сундук показывает одну строчку, написанную вами, и как давно. Ваши слова — вам обратно, и они не покидают это устройство.",
            ee: "Iga päev näitab laegas ühte sinu enda kirjutatud rida ja kui ammu. Sinu sõnad sulle tagasi — ja need ei lahku sellest seadmest." },
    where: "chest" },
  { id: "letter", kind: "letter", params: { days: 30 }, tier: "rare",
    title: { en: "A letter to yourself", ru: "Письмо себе", ee: "Kiri iseendale" },
    what: { en: "Write it now. It is sealed for thirty days, then arrives in your Notes on its own.",
            ru: "Напишите его сейчас. Оно запечатано на тридцать дней, потом само придёт в Записи.",
            ee: "Kirjuta see nüüd. See on pitseeritud kolmkümmend päeva, siis jõuab ise sinu Märkmetesse." },
    where: "chest" },
  { id: "system-letter", kind: "systemletter", params: {}, tier: "discovery",
    title: { en: "A letter from the system", ru: "Письмо от системы", ee: "Kiri süsteemilt" },
    what: { en: "The system writes to you once — with your real numbers, in your language. It lands in your Notes.",
            ru: "Система пишет вам один раз — с вашими настоящими числами, на вашем языке. Письмо ложится в Записи.",
            ee: "Süsteem kirjutab sulle ühe korra — sinu tegelike arvudega, sinu keeles. Kiri jõuab sinu Märkmetesse." },
    where: "notes" },
  /* ── ЖИВОЕ: ТО, ЧТО ЧУВСТВУЕТСЯ КАЖДЫЙ ДЕНЬ ──────────────────────────── */
  { id: "night", kind: "night", params: {}, tier: "discovery", switch: true,
    title: { en: "Night on its own", ru: "Ночь сама", ee: "Öö iseenesest" },
    what: { en: "After midnight the desk slips into Ember by itself; in the morning it brings your room back. Living time, not another theme.",
            ru: "После полуночи стол сам уходит в Угли; утром возвращает вашу комнату. Живое время, а не ещё одна тема.",
            ee: "Pärast keskööd libiseb laud ise Hõõgusesse; hommikul toob sinu toa tagasi. Elav aeg, mitte järjekordne teema." },
    where: "settings" },
  { id: "rename", kind: "rename", params: {}, tier: "discovery", switch: true,
    title: { en: "Your own names for rooms", ru: "Своё имя комнатам", ee: "Sinu oma nimed tubadele" },
    what: { en: "Rename any room in the dock — «Notes» can become «Diary». The system takes on your meaning, not just your look.",
            ru: "Переименуйте любую комнату в доке — «Записи» могут стать «Дневником». Система получает ваш смысл, а не только ваш вид.",
            ee: "Nimeta ümber ükskõik milline tuba dokis — «Märkmed» võib saada «Päevikuks». Süsteem saab sinu tähenduse, mitte ainult sinu välimuse." },
    where: "chest" },
  { id: "countdown", kind: "countdown", params: {}, tier: "joy", switch: true,
    title: { en: "A counter on the desk", ru: "Счётчик на столе", ee: "Loendur laual" },
    what: { en: "A sticky note that counts the days to your date by itself. Part of the desk every morning, not a picture seen once.",
            ru: "Заметка на столе, которая сама считает дни до вашей даты. Каждое утро — часть стола, а не картинка на один раз.",
            ee: "Märge laual, mis loeb ise päevi sinu kuupäevani. Igal hommikul osa lauast, mitte ühekordne pilt." },
    where: "chest" },
  { id: "saver", kind: "saver", params: { minutes: 3 }, tier: "discovery", switch: true,
    title: { en: "Screensaver", ru: "Заставка", ee: "Ekraanisäästja" },
    what: { en: "Leave the desk still for three minutes and it dims into a quiet field with the clock and tonight's moon. Any touch brings it back.",
            ru: "Оставьте стол без движения на три минуты — он гаснет в тихое поле с часами и сегодняшней луной. Любое касание возвращает.",
            ee: "Jäta laud kolmeks minutiks liikumatuks — see hämardub vaikseks väljaks kella ja tänase kuuga. Iga puudutus toob tagasi." },
    where: "chest" },
  { id: "solitaire", kind: "room", params: { room: "solitaire" }, tier: "rare",
    title: { en: "Solitaire", ru: "Пасьянс", ee: "Pasjanss" },
    what: { en: "A quiet game room that only the chest can open. Tap a card, tap where it goes; the deal waits for you between visits.",
            ru: "Тихая игра-комната, которую открывает только сундук. Коснитесь карты, коснитесь места; расклад ждёт вас между визитами.",
            ee: "Vaikne mängutuba, mille avab ainult laegas. Puuduta kaarti, puuduta kohta; kaardid ootavad sind külastuste vahel." },
    where: "solitaire" }
];
